apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: elk-nudge
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: elk-nudge
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgsync-configmap
  namespace: elk-nudge
data:
  ELASTICSEARCH_HOST: quickstart-es-http
  REDIS_HOST: redis-service
  SCHEMA: smfood.json
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-config-volume-pv
  namespace: elk-nudge
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/local/schema"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: pg-config-volume-pvc
  namespace: elk-nudge
spec:
  storageClassName: generic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsync-deployment
  namespace: elk-nudge
  labels:
    app: pgsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsync
  template:
    metadata:
      labels:
        app: pgsync
    spec:
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-config-volume-pvc
      containers:
      - name: pgsync
        image: docker.io/behnood/v20-pg-elk
        command: ["./runserver.sh"]
        volumeMounts:
        - mountPath: /schema/
          name: pg-data
        ports:
        - containerPort: 27017
        env:
        - name: PG_USER
          value: "nudge"
        - name: PG_HOST
          value: "nudge.cb1vpgtb09ue.us-east-1.rds.amazonaws.com"
        - name: PG_PORT
          value: "5432"
        - name: PG_PASSWORD
          value: "admin-admin"
        - name: ELASTICSEARCH_USER
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "elk@nudge-7469"
        - name: REPLICATION_SLOT_CLEANUP_INTERVAL
          value: "5"
        - name: ELASTICSEARCH_HOST
          value: "quickstart-es-internal-http"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: CHECKPOINT_PATH
          value: "/schema/"
        - name: SCRIPT
          value: "bootstrap-pgsync"
        - name: SCHEMA
          value: "cpg.json"
        - name: ME_CONFIG_PGSYNC_SERVICE
          valueFrom:
            configMapKeyRef:
              name: pgsync-configmap
              key: ELASTICSEARCH_HOST
        - name: ME_CONFIG_PGSYNC_SERVICE_REDIS
          valueFrom:
            configMapKeyRef:
              name: pgsync-configmap
              key: REDIS_HOST

---

apiVersion: v1
kind: Service
metadata:
  name: pgsync-service
  namespace: elk-nudge
spec:
  selector:
    app: pgsync
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
